FROM golang:1.17 as builder
WORKDIR /go/src/github.com/zuri03/GoCloudStore/

COPY cli ./Cli
COPY go.mod .
COPY ./cmd/cli/main.go .

RUN CGO_ENABLED=0 go build -o  build/Cli ./main.go
FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /go/src/github.com/zuri03/GoCloudStore/
COPY --from=builder /go/src/github.com/zuri03/GoCloudStore/build/Cli ./main
ENTRYPOINT [ "./main" ]