FROM golang:1.17 as builder
WORKDIR /go/src/github.com/zuri03/GoCloudStore/

COPY records ./records
COPY go.mod .
COPY ./cmd/records/main.go .

RUN CGO_ENABLED=0 go build -o  build/Records ./main.go
FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /go/src/github.com/zuri03/GoCloudStore/
COPY --from=builder /go/src/github.com/zuri03/GoCloudStore/build/Records ./main
EXPOSE 8080
ENTRYPOINT [ "./main" ]