version: '3'

services:

  records:
    image: record_service
    environment:
      - MONGO_URI=${MONGO_URI}
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.records
    ports:
     - "8080:8080"
    container_name: records
    depends_on:
      - mongo
    restart: unless-stopped
  
  user:
    image: user_service
    environment:
      - MONGO_URI=${MONGO_URI}
    build:
      context: .
      dockerfile: ./deployments/dev/Dockerfile.user
    ports:
      - "9000:9000"
    container_name: user
    depends_on:
      - mongo
    restart: unless-stopped

  storage:
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.storage
    ports:
      - "8000:8000"
    container_name: storage

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  