#Two services so far
  #record keeper
  #storage
#docker compose is for devlopment purposes only until I learn to use kubernetes
version: '3'
services:
  records:
    build: 
      context: .
      dockerfile: ./docker/deployments/Dockerfile.records
    ports:
     - '8080:8080'
  storage:
    build: 
      context: .
      dockerfile: ./docker/deployments/Dockerfile.storage
    ports:
      - '8000:8000'

  