#Two services so far
  #record keeper
  #storage
#docker compose is for devlopment purposes only until I learn to use kubernetes
version: '3'
services:
  records:
    image: record_server
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.records
    ports:
     - "8080:8080"
    container_name: records
    depends_on:
      - mongo
    restart: unless-stopped
  storage:
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.storage
    ports:
      - "8000:8000"
    container_name: storage
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  