#Two services so far
  #record keeper
  #storage
#docker compose is for devlopment purposes only until I learn to use kubernetes
version: '3'
services:
  records:
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.records
    ports:
     - '8080:8080'
  storage:
    build: 
      context: .
      dockerfile: ./deployments/dev/Dockerfile.storage
    ports:
      - '8000:8000'
  users:
    build:
      context: .
      dockerfile: ./deployments/dev/Dockerfile.users
    ports:
      - '9000:9000'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  redis:
    image: redis:latest

  