FROM golang:1.17 as builder
WORKDIR /go/src/github.com/zuri03/GoCloudStore/

COPY users ./users
COPY records ./records
COPY go.mod .
COPY go.sum .
COPY ./cmd/users/main.go .


RUN CGO_ENABLED=0 go build -o  build/users ./main.go
FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /go/src/github.com/zuri03/GoCloudStore/
COPY --from=builder /go/src/github.com/zuri03/GoCloudStore/build/users ./main
EXPOSE 9000
ENTRYPOINT [ "./main" ]