FROM golang:1.17 as builder

WORKDIR /go/src

COPY records ./records
COPY common ./common

#copies over go mod and go sum
COPY go.* .
COPY ./cmd/records/main.go .

#download and verify any missing dependencies
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 go build -o  build/Records ./main.go

FROM alpine:latest  
RUN apk --no-cache add ca-certificates

#RUN useradd -c "Docker Image" records
#USER records

WORKDIR /go/src/github.com/zuri03/GoCloudStore/
COPY --from=builder /go/src/build/Records ./main
EXPOSE 8080
ENTRYPOINT [ "./main" ]